baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Ayaã®ğŸ¸Room"

# whether to use robots.txt
# æ˜¯å¦ä½¿ç”¨ robots.txt
enableRobotsTXT = true
# whether to use git commit log
# æ˜¯å¦ä½¿ç”¨ git ä¿¡æ¯
enableGitInfo = true
# whether to use emoji code
# æ˜¯å¦ä½¿ç”¨ emoji ä»£ç 
enableEmoji = true

# Change the default theme to be use when building the site with Hugo
theme = "DoIt"

[params]
  # LoveIt theme version
  version = "0.2.X"

  description = "About LoveIt Theme"
  # site keywords
  keywords = ["Theme", "Hugo"]

  # date format
  dateFormat = "2006-01-02"

  enablePWA = true

  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'


  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/York-Shawn/blog"
  

  [params.header]
    desktopMode = "fix"

    mobileMode = "auto"

    [params.header.title]
      pre = '<i class="fas fa-code"></i>'
      name = "Aya"
      typeit = true
    [params.footer]
      enable = true
      # Custom content (HTML format is supported)
      # è‡ªå®šä¹‰å†…å®¹ (æ”¯æŒ HTML æ ¼å¼)
      custom = ''
      # whether to show Hugo and theme info
      # æ˜¯å¦æ˜¾ç¤º Hugo å’Œä¸»é¢˜ä¿¡æ¯
      hugo = true
      # whether to show copyright info
      # æ˜¯å¦æ˜¾ç¤ºç‰ˆæƒä¿¡æ¯
      copyright = true
      # whether to show the author
      # æ˜¯å¦æ˜¾ç¤ºä½œè€…
      author = true
      # site creation time
      # ç½‘ç«™åˆ›ç«‹å¹´ä»½
      since = 2019

      license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10
    [params.section.recentlyUpdated]
      enable = true
      rss = true
      days = 30
      maxCount = 10
  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss =10
  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    # æ¯ä¸€æ­¥çš„æ‰“å­—é€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    # å…‰æ ‡çš„é—ªçƒé€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    # å…‰æ ‡çš„å­—ç¬¦ (æ”¯æŒ HTML æ ¼å¼)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    # æ‰“å­—ç»“æŸä¹‹åå…‰æ ‡çš„æŒç»­æ—¶é—´ (å•ä½æ˜¯æ¯«ç§’, "-1" ä»£è¡¨æ— é™å¤§)
    duration = -1
  [params.page]

    twemoji = true
    lightgallery = true
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = true
    seriesNavigation = true
    linkToEdit = "https://github.com/York-Shawn/blog/tree/main/content/{path}"
    rssFullText = false
    pageStyle = "normal"
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    [params.page.code]
      copy = true
      maxShownLines = 10
    [params.page.math]
      enable = false
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      # é»˜è®¤å—å®šç•Œç¬¦æ˜¯ $$ ... $$ å’Œ \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      # é»˜è®¤è¡Œå†…å®šç•Œç¬¦æ˜¯ $ ... $ å’Œ \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX extension copy_tex
      # KaTeX æ’ä»¶ copy_tex
      copyTex = true
      # KaTeX extension mhchem
      # KaTeX æ’ä»¶ mhchem
      mhchem = true
    [params.page.mapbox]
      # access token of Mapbox GL JS
      # Mapbox GL JS çš„ access token
      accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
      # style for the light theme
      # æµ…è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      # style for the dark theme
      # æ·±è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      # whether to add NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
      # æ˜¯å¦æ·»åŠ  NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
      navigation = true
      # whether to add GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
      # æ˜¯å¦æ·»åŠ  GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
      geolocate = true
      # whether to add ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
      # æ˜¯å¦æ·»åŠ  ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
      scale = true
      # whether to add FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
      # æ˜¯å¦æ·»åŠ  FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
      fullscreen = true
    [params.page.share]
      enable = true
      Linkedin = true
      Twitter = true
      Reddit = true
    [params.page.comment]
      enable = true
      [params.page.comment.valine]
        enable = false
        appId = "QGzwQXOqs5JOhN4RGPOkR2mR-MdYXbMMI"
        appKey = "WBmoGyJtbqUswvfLh6L8iEBr"
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = "https://leancloud.hugoloveit.com"
        emoji = ""
            # Waline comment config (https://waline.js.org/)
      # Waline è¯„è®ºç³»ç»Ÿè®¾ç½® (https://waline.js.org/)
            # Waline comment config (https://waline.js.org/)
      # Waline è¯„è®ºç³»ç»Ÿè®¾ç½® (https://waline.js.org/)
      [params.page.comment.waline]
        enable = true
        serverURL = "https://waline-york-shawn.vercel.app/"                 							# Walineçš„æœåŠ¡ç«¯åœ°å€ï¼ˆå¿…å¡«ï¼‰ 
        visitor = true
        emoji = ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
        meta = ['nick', 'mail', 'link']
        requiredMeta = []
        login = 'enable'
        wordLimit = 0
        pageSize = 10
        uploadImage = true
        highlight = true
        mathTagSupport = false
        commentCount = true                                       # ä»£ç é«˜äº®

  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Ayaã®Guitar Room"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"
  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "fuse"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # max number of results length
    maxResultLength = 10
    # snippet length of the result
    snippetLength = 30
    # HTML tag name of the highlight part in results
    highlightTag = "em"
    # whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.fuse]
      # https://fusejs.io/api/options.html
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.1
      distance = 100
      ignoreLocation = true
      useExtendedSearch = false
      ignoreFieldNorm = false
  [params.home]    
    # amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/avatar.jpg"
      # title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page
      subtitle = "æ‚²ã—ã„ã“ã¨ã‚’æ¶ˆã—ãŸã„<br>å¬‰ã—ã„ã“ã¨ã‚‚æ¶ˆã—ãŸã„<br>å¿ƒã‚’æ¶ˆã—ãŸã„"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
  [params.social]
    github = "York-Shawn"
    Twitter = "BigSnakeShawn"
    Bilibili = "6804357"
    Email = "yorkshawn007@gmail.com"
    RSS = true
[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "series"
    pre = ""
    post = ""
    name = "Series"
    url = "/series/"
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 8
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    post = ""
    name = ""
    url = "https://github.com/York-Shawn"
    title = "GitHub"
    weight = 9

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      # æ˜¯å¦åœ¨æ–‡æ¡£ä¸­ç›´æ¥ä½¿ç”¨ HTML æ ‡ç­¾
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[author]
  name = "Aya"
  email = "yorkshawn007@gmail.com"

# Options to make output .md files
# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
# ç”¨äº Hugo è¾“å‡ºæ–‡æ¡£çš„è®¾ç½®
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

# Options for taxonomies
# ç”¨äºåˆ†ç±»çš„è®¾ç½®
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

